<?php

namespace AppBundle\Repository;

/**
 * AppPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppPreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
