<?php

namespace AppBundle\Repository;

/**
 * CommentLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentLogRepository extends \Doctrine\ORM\EntityRepository
{
}
