<?php

namespace AppBundle\Repository;

/**
 * HostingOrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostingOrganizationRepository extends \Doctrine\ORM\EntityRepository
{
}
