<?php

namespace AppBundle\Repository;

/**
 * ManuscriptReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManuscriptReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
