<?php

namespace AppBundle\Repository;

/**
 * MilitaryUnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilitaryUnitRepository extends \Doctrine\ORM\EntityRepository
{
}
