<?php

namespace AppBundle\Repository;

/**
 * PlaceNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceNameRepository extends \Doctrine\ORM\EntityRepository
{
}
