<?php

namespace AppBundle\Repository;

/**
 * PrintedReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintedReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
