<?php

namespace AppBundle\Repository;

/**
 * ReferenceItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceItemRepository extends \Doctrine\ORM\EntityRepository
{
}
