<?php

namespace AppBundle\Repository;

/**
 * TaxonomyVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxonomyVersionRepository extends \Doctrine\ORM\EntityRepository
{
}
