<?php

namespace AppBundle\Repository;

/**
 * TrainingResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingResultRepository extends \Doctrine\ORM\EntityRepository
{
}
