<?php

namespace AppBundle\Repository;

/**
 * TrainingContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingContentRepository extends \Doctrine\ORM\EntityRepository
{
}
