<?php

namespace AppBundle\Repository;

/**
 * TranscriptLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranscriptLogRepository extends \Doctrine\ORM\EntityRepository
{
}
