<?php

namespace AppBundle\Repository;

/**
 * WillTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WillTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
