<?php

namespace DataBundle\Repository;

/**
 * TestatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestatorRepository extends \Doctrine\ORM\EntityRepository
{
}
