<?php

namespace DataBundle\Repository;

/**
 * WillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WillRepository extends \Doctrine\ORM\EntityRepository
{
}
