<?php

namespace TranscriptBundle\Repository;

/**
 * TranscriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranscriptRepository extends \Doctrine\ORM\EntityRepository
{
}
